---
system_parameters:
    volume_file_name: "../../data/cylinder/cylinder3_770.vtk"
    observation_file_name: "obs_testing/cylinder3_770"
    observation_points_file_name: "../../data/cylinder/cyl10_4245_obs33.vtk"

general_parameters:
    gravity: [0.0, 0.0, 0.0]
    density: 200 # total_mass: 0.2
    delta_time: 0.01
    solver_kind: "Symplectic"   # options are "Euler", "Newton", and "Symplectic"
    da_solver_kind: "Euler"   # options are "Euler", "Newton", and "Symplectic"
    linear_solver_kind: "Pardiso"   # options are "CG" and "Pardiso"
    rayleigh_mass: 0.1
    rayleigh_stiffness: 0.1
    boundary_conditions_list:
        - condition_type: "fixed"   # options are "fixed" and "elastic"
          boxes_coordinates: "-0.05 -0.05 -0.002 0.05 0.05 0.002   -0.05 -0.05 0.238 0.05 0.05 0.242"

obs_generating_parameters:
    object_young_moduli: "1500 6000 2000"
    save_observations: 1

filtering_parameters:
    output_directory_prefix: "outCyl3_770_"
    output_directory_suffix: "_cyl3RestShape_init500"
    output_files_suffix: "test"
    optim_params_size: 2
    filter_kind: "ROUKF"   # options are "ROUKF", "UKFSimCorr", and "UKFClassic"
    use_unbiased_variance: "0"
    initial_stiffness: [1000, 1000]
    minimal_stiffness: [300, 300]
    maximal_stiffness: [100000, 100000]
    initial_standart_deviation: 500
    observation_noise_standart_deviation: 1e-3
    positions_standart_deviation: 1e-6
    transform_parameters: project
    sigma_points_topology: "Simplex"   # options are "Simplex" and "Star"
    sigma_points_scale: 1
    save_state: 1
    save_internal_data: 1

impact_parameters:
    observation_file_name: "obs_testing/cylinder3impact"
    position: "0.0 -0.02 0.107"
    bound: "-0.01 -0.02 0.1 0.01 -0.01 0.11"

time_parameters:
    computation_time_file_name: "computationTime.txt"
...

