---
system_parameters:
    volume_file_name: "../../data/baseLiver/baseLiver.msh"
    observation_file_name: "obs_testing/livergeomagic"
    observation_points_file_name: "../../data/baseLiver/baseLiverGen_obs7_variant2.vtk"

general_parameters:
    gravity: [0, 0, 0]
    density: 200 # total_mass: 0.2
    delta_time: 0.01
    solver_kind: "Euler"   # options are "Euler", "Newton", and "Symplectic"
    linear_solver_kind: "LDL"   # options are "CG", "Pardiso", and "LDL"
    rayleigh_mass: 0.1
    rayleigh_stiffness: 0.1
    boundary_conditions_list:
        - condition_type: "elastic"   # options are "fixed" and "elastic"
          boxes_coordinates: "0.11 0.245 0.355 0.12 0.255 0.365  0.295 0.26 0.34 0.305 0.27 0.35 0.2 0.27 0.365 0.21 0.28 0.375"
          spring_stiffness_values: "150 300 200"

obs_generating_parameters:
    object_young_moduli: "150 300 200"
    save_observations: 1

filtering_parameters:
    output_directory_prefix: "outCyl2_138_"
    output_directory_suffix: "_liverGeomagic7observationsCuttingTest"
    output_files_suffix: "test" 
    optim_params_size: 3
    filter_kind: "ROUKF"   # options are "ROUKF", "UKFSimCorr", and "UKFClassic"
    use_unbiased_variance: "0"
    initial_stiffness: [150, 300, 200]
    minimal_stiffness: [8, 8, 8]
    maximal_stiffness: [100000, 100000, 100000]
    initial_standart_deviation: 4
    observation_noise_standart_deviation: 1e-3
    positions_standart_deviation: 1e-3
    transform_parameters: project
    sigma_points_topology: "Simplex"   # options are "Simplex" and "Star"
    sigma_points_scale: 1
    save_state: 1
    save_internal_data: 1

impact_parameters:
    observation_file_name: "obs_testing/liverGeomagicImpact"
    position: "0.144 0.154 0.398"

time_parameters:
    computation_time_file_name: "computationTime.txt"
...

